### ISSUE TITLE
Possible to add card withouth ayano ?

### ISSUE THREAD

**Issue by setsuk12** [NoxCaos/amusementclub2.0#46]
hello I'm trying to learn how to use the bot

how to add maps without using ayano? I can't understand how it works

thanks

**Comment by NoxCaos** [comment]
Hi, if you are running bot in the test mode without Ayano the only way to add more cards is to manually populate [cards.json](https://github.com/NoxCaos/amusementclub2.0/blob/master/test/data/cards.json) and [collections.json](https://github.com/NoxCaos/amusementclub2.0/blob/master/test/data/collections.json)
